config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  get 'admin' => 'admin#index'
   controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
   end

  resources :users
  resources :orders
  get 'store/index'

  resources :tickets

  root to: 'store#index', as: 'store'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

	has_many :tickets
	
	validates :name, :city, :email, presence: true

	def add_line_items_from_ticket(ticket)
		ticket.line_items.each do |item|
			item.ticket_id = nil
			line_items << item
		end
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: [:new, :create]
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    
    @order = Order.new(order_params)  
    @order.add_line_items_from_ticket(current_ticket)

    respond_to do |format|
      if @order.save
        format.html { redirect_to store_path, notice: 'Order was successfully created.' }
        
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :city, :email)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<html>
<body id = "baca">
<div class="fixed-crossbrowser-background"></div>
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Igor', :pattern => '\D[^0-9~!@№#$%:,^&.*()_+={};:<>"\s]{1,20}', :required => true %>
  </div>

  <div class="field">
    <%= f.label :city , t('city')%>
    <%= f.text_field :city, placeholder: 'Lviv', :pattern => '\D[^0-9~!@№#$%:,^&.*()_+={};:<>"\s]{1,20}', :required => true %>
  </div>
  <div class="field">
    <%= f.label :email , t('email') %>
    <%= f.email_field :email, placeholder: 'pivorak@gmail.com', :pattern => '^[A-Za-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$', :required => true  %>
    <span class="form_hint"><%='pivorak@gmail.com'%></span>
  
  <div class="actions">
    <%= f.submit 'Make Order', :class => 'submit' %>
  </div>


<% end %>


</body>
</html>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>City</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        
        <td><%= order.id %></td>
        <td><%= order.name %></td>
        <td><%= order.city %></td>
        <td><%= order.email %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div id="orders_area">
	<span class="header"><%= 'New order'%></span>
<span class="required_notification"><%= 'Fields must be required'%></span>



<%= render 'form' %>

</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>