config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  get 'admin' => 'admin#index'
   controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
   end

  resources :users
  resources :orders
  get 'store/index'

  resources :tickets

  root to: 'store#index', as: 'store'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord

	
	has_many :line_items

	has_many :orders, through: :line_items


	validates :count, :place, :arrive, :departure, :image_url, presence: true

	validates :price, numericality: {greater_than_or_equal_to: 0.01}

	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)}i,
		message: ' must be a URL for GIF, JPG or PNG image.'
	}
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    
     @ticket = Ticket.new(ticket_params)


    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
         
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:count, :place, :arrive, :departure, :image_url, :price)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(ticket) do |f| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count %>
    <%= f.number_field :count %>
  </div>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>

  <div class="field">
    <%= f.label :arrive %>
    <%= f.text_field :arrive %>
  </div>

  <div class="field">
    <%= f.label :departure %>
    <%= f.text_field :departure %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

  <div class="new"><%= link_to 'New Ticket', new_ticket_path%></div>

  <div class="itemz">
  <% @tickets.each do |ticket| %>
     <div class="item">
      <%= image_tag(ticket.image_url, class:'list_image')%>
      
       <br/>
      <i><%= ticket.count %></i>
      <br/>
      
      <i><%= ticket.place %></i>
            
      <br/>
      <i><%= ticket.arrive %></i>
            
      <br/>
            
      <i><%= ticket.departure %></i>
            
      <br/>

       <div id="prci"><%= sprintf("₴%0.02f",ticket.price, :unit => 'UAH', format: "%n %u") %></div>

      <br/>
     
     <div class="show"> <%= link_to 'Show', ticket %></div>
     <div class="edit"> <%= link_to 'Edit', edit_ticket_path(ticket) %></div>
     <div class="destroy"> <%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></div><br/>
   

  </div>
  

<% end %>


</div>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p>
  <strong>Count:</strong>
  <%= @ticket.count %>
</p>

<p>
  <strong>Place:</strong>
  <%= @ticket.place %>
</p>

<p>
  <strong>Arrive:</strong>
  <%= @ticket.arrive %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @ticket.departure %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @ticket.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>